name: flutter_libphonenumber
description: Leverages libphonenumber to allow for asynchronous and synchronous formatting of phone numbers in Flutter apps.
version: 2.0.0

environment:
  sdk: ">=2.19.0 <4.0.0"
  flutter: ">=3.0.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: flutter_libphonenumber_android
      ios:
        default_package: flutter_libphonenumber_ios
      # web:
      #   default_package: url_launcher_web
      # linux:
      #   default_package: url_launcher_linux
      # macos:
      #   default_package: url_launcher_macos
      # windows:
      #   default_package: url_launcher_windows

dependencies:
  flutter:
    sdk: flutter
  flutter_libphonenumber_android: ^1.0.0
  flutter_libphonenumber_ios: ^1.0.0
  flutter_libphonenumber_platform_interface: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.1.4
