name: flutter_libphonenumber_android
description: Android implementation of the flutter_libphonenumber plugin.
version: 1.0.0

environment:
  sdk: ">=2.19.0 <4.0.0"
  flutter: ">=3.0.0"

flutter:
  plugin:
    implements: flutter_libphonenumber
    platforms:
      android:
        package: com.bottlepay.flutter_libphonenumber_android
        pluginClass: FlutterLibphonenumberAndroidPlugin
        dartPluginClass: FlutterLibphonenumberAndroid

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
